/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author anonu
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }

    public boolean validateInput(){
        try {
            // Ensure BookId field is not empty and contains a valid integer
            if (txt_returnbookid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the book ID");
                return false;
            }
            String BookId = txt_returnbookid.getText();

            // Ensure StudentId field is not empty and contains a valid integer
            if (txt_returnstudentid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the student ID");
                return false;
            }
            int StudentId = Integer.parseInt(txt_returnstudentid.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for book ID and student ID");
            return false;
        }
       return true;
    }
    
//    update bookcount
    public void updateBookCount(){
        String BookId = txt_returnbookid.getText();

        try{
            Connection conn = DBConnection.getConnection();
            String sql = "UPDATE book_details SET quantity = quantity + 1 WHERE book_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, BookId);

            int rowCount = pst.executeUpdate();
            if(rowCount > 0){
                JOptionPane.showMessageDialog(this, "Book count updated.");
            }else{
                JOptionPane.showMessageDialog(this, "Cannot update book count.");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

//    to fetch issue details
    public void getIssueDetails(){
        String BookId = txt_returnbookid.getText();
        int StudentId = Integer.parseInt(txt_returnstudentid.getText());
        try{
            Connection conn = DBConnection.getConnection();
            PreparedStatement pst = conn.prepareStatement("SELECT * from issue_book WHERE book_id = ? AND student_id = ? AND status = ?");

            pst.setString(1, BookId);
            pst.setInt(2, StudentId);
            pst.setString(3, "pending");
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                lbl_issueid.setText(rs.getString("id"));
                lbl_bookname.setText("<html>" + rs.getString("book_name") + "</html>");
                lbl_studentname.setText(rs.getString("student_name"));
                lbl_issuedate.setText(rs.getString("issue_date"));
                lbl_duedate.setText(rs.getString("due_date"));   
                lbl_bookinvalid.setText("");
            }else{
                lbl_bookinvalid.setText("NO RECORD FOUND.");
                
                lbl_issueid.setText("");
                lbl_bookname.setText("");
                lbl_studentname.setText("");
                lbl_issuedate.setText("");
                lbl_duedate.setText("");   
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
//  return the book to 
    public boolean returnBook(){
        boolean isReturned = false;
        String BookId = txt_returnbookid.getText();
        int StudentId = Integer.parseInt(txt_returnstudentid.getText());
        
        try{
            Connection conn = DBConnection.getConnection();
            String sql = "UPDATE issue_book SET status = ? WHERE student_id = ? AND book_id = ? AND status = ?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, "returned");
            pst.setInt(2, StudentId);
            pst.setString(3, BookId);
            pst.setString(4, "pending");
            
           int rowCount = pst.executeUpdate();
            if(rowCount > 0){
                isReturned = true; 
            }else{
                isReturned = false;
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return isReturned;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_bookinvalid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_issuedate = new javax.swing.JLabel();
        lbl_issueid = new javax.swing.JLabel();
        lbl_bookname = new javax.swing.JLabel();
        lbl_studentname = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_duedate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_exit1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_returnbookid = new app.bolivia.swing.JCTextField();
        txt_returnstudentid = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_returnbook = new rojerusan.RSMaterialButtonRectangle();
        btn_find = new rojerusan.RSMaterialButtonRectangle();

        jPanel7.setPreferredSize(new java.awt.Dimension(400, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 900));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText("Back");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 111, 37));

        jPanel3.setBackground(new java.awt.Color(27, 23, 23));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 900));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        lbl_bookinvalid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_bookinvalid.setForeground(new java.awt.Color(204, 0, 0));
        lbl_bookinvalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lbl_bookinvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 380, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Book Name:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Issue ID:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lbl_issuedate.setBackground(new java.awt.Color(238, 235, 221));
        lbl_issuedate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_issuedate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbl_issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 170, 30));

        lbl_issueid.setBackground(new java.awt.Color(238, 235, 221));
        lbl_issueid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_issueid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbl_issueid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 170, 30));

        lbl_bookname.setBackground(new java.awt.Color(238, 235, 221));
        lbl_bookname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bookname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bookname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_bookname.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(lbl_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 200, 140));

        lbl_studentname.setBackground(new java.awt.Color(238, 235, 221));
        lbl_studentname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_studentname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbl_studentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 170, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel9.setText("Book Details");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 5));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 330, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Issue Date: ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Due Date: ");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        lbl_duedate.setBackground(new java.awt.Color(238, 235, 221));
        lbl_duedate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_duedate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbl_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 170, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel1.setText("Return Book");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 330, -1));

        jLabel_exit1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_exit1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel_exit1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_exit1.setText("X");
        jLabel_exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exit1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Book ID:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        txt_returnbookid.setBackground(new java.awt.Color(238, 235, 221));
        txt_returnbookid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_returnbookid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_returnbookid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txt_returnbookid.setPlaceholder("Enter book ID");
        txt_returnbookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_returnbookidFocusLost(evt);
            }
        });
        txt_returnbookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_returnbookidActionPerformed(evt);
            }
        });
        jPanel2.add(txt_returnbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 380, 50));

        txt_returnstudentid.setBackground(new java.awt.Color(238, 235, 221));
        txt_returnstudentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_returnstudentid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_returnstudentid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txt_returnstudentid.setPlaceholder("Enter student ID");
        txt_returnstudentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_returnstudentidFocusLost(evt);
            }
        });
        jPanel2.add(txt_returnstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 380, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Student ID:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        btn_returnbook.setBackground(new java.awt.Color(27, 23, 23));
        btn_returnbook.setText("Return Book");
        btn_returnbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_returnbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_returnbookMouseClicked(evt);
            }
        });
        btn_returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnbookActionPerformed(evt);
            }
        });
        jPanel2.add(btn_returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 350, -1));

        btn_find.setBackground(new java.awt.Color(27, 23, 23));
        btn_find.setText("Find");
        btn_find.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_find.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_findMouseClicked(evt);
            }
        });
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });
        jPanel2.add(btn_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 350, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        HomePage homepage = new HomePage();
        homepage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exit1MouseClicked

    private void txt_returnbookidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_returnbookidFocusLost

    }//GEN-LAST:event_txt_returnbookidFocusLost

    private void txt_returnstudentidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_returnstudentidFocusLost

    }//GEN-LAST:event_txt_returnstudentidFocusLost

    private void btn_returnbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnbookMouseClicked

    }//GEN-LAST:event_btn_returnbookMouseClicked

    private void btn_returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnbookActionPerformed
        if(validateInput()){
            if(returnBook() == true){
                JOptionPane.showMessageDialog(this, "Book returned successfully.");
                updateBookCount();
            }else{
                JOptionPane.showMessageDialog(this, "Book Returned Failed.");
            }
        }
    }//GEN-LAST:event_btn_returnbookActionPerformed

    private void txt_returnbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_returnbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_returnbookidActionPerformed

    private void btn_findMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_findMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_findMouseClicked

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        if(validateInput()){
            getIssueDetails();
        }
    }//GEN-LAST:event_btn_findActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        lbl_issueid.setText("");
        lbl_bookname.setText("");
        lbl_studentname.setText("");
        lbl_issuedate.setText("");
        lbl_duedate.setText("");   
        lbl_bookinvalid.setText("");
        
        txt_returnbookid.setText("");
        txt_returnstudentid.setText("");
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_find;
    private rojerusan.RSMaterialButtonRectangle btn_returnbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_exit1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_bookinvalid;
    private javax.swing.JLabel lbl_bookname;
    private javax.swing.JLabel lbl_duedate;
    private javax.swing.JLabel lbl_issuedate;
    private javax.swing.JLabel lbl_issueid;
    private javax.swing.JLabel lbl_studentname;
    private app.bolivia.swing.JCTextField txt_returnbookid;
    private app.bolivia.swing.JCTextField txt_returnstudentid;
    // End of variables declaration//GEN-END:variables
}
