package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.xml.bind.DatatypeConverter;

public class Signup extends javax.swing.JFrame {
    
    public Signup(){
        initComponents();
    }
    
    public static String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(password.getBytes());
            byte[] digest = md.digest();
            return DatatypeConverter.printHexBinary(digest).toLowerCase();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
//    methdod to insert in user table
    public void InsertSignupDetails() {
        String username = txt_username.getText();
        String password = new String(txt_password.getPassword());
        String confirm_password = new String(txt_repassword.getPassword());

        if (!password.equals(confirm_password)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }

        String hashedPassword = Signup.hashPassword(password);

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pst = conn.prepareStatement("INSERT INTO users(username, password) VALUES(?,?)")) {

            pst.setString(1, username);
            pst.setString(2, hashedPassword);

            int updatedRowCount = pst.executeUpdate();

            if (updatedRowCount > 0) {
                JOptionPane.showMessageDialog(this, "Record inserted successfully");
                Login login = new Login();
                login.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Record insertion failed");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage());
        }
    }
//    Validations
    public boolean validateSignup(){
        String username = txt_username.getText();
        String password = new String(txt_password.getPassword());
        String confirm_password = new String(txt_repassword.getPassword());
        
        if(username.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a username");
            return false;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter password");
            return false;
        }
        if(confirm_password.equals("")){
            JOptionPane.showMessageDialog(this, "Please confirm your password");
            return false;
        }
        if(password.length() < 8){
            JOptionPane.showMessageDialog(this, "Password must be atleast 8 characters");
            return false;
        }
        return true;
    }
    
//    Duplication check
    public boolean checkDuplicateUser(){
        String username = txt_username.getText();
        boolean isExist = false;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DBConnection.getConnection();
            
            PreparedStatement pst = conn.prepareStatement("SELECT * from users WHERE username = ?");
            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExist = true;
            }else{
                isExist = false;
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return isExist;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_exit = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_signup = new rojerusan.RSMaterialButtonRectangle();
        btn_relogin = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_repassword = new javax.swing.JPasswordField();
        txt_password = new javax.swing.JPasswordField();
        hidere = new javax.swing.JCheckBox();
        hidepass = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 227, 219));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_exit.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel_exit.setText("X");
        jLabel_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 0, -1, -1));

        txt_username.setBackground(new java.awt.Color(242, 227, 219));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_username.setPlaceholder("Enter username");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 259, 340, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 216, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 326, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Already have an account?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 720, -1, -1));

        btn_signup.setBackground(new java.awt.Color(232, 106, 51));
        btn_signup.setForeground(new java.awt.Color(0, 0, 0));
        btn_signup.setText("Signup");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel1.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 536, 261, 92));

        btn_relogin.setBackground(new java.awt.Color(232, 106, 51));
        btn_relogin.setText("Login here");
        btn_relogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reloginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_relogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 712, 132, 47));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 429, -1, -1));

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 64)); // NOI18N
        jLabel8.setText("Sign up");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 28, -1, 182));

        txt_repassword.setBackground(new java.awt.Color(242, 227, 219));
        txt_repassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_repassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 340, 40));

        txt_password.setBackground(new java.awt.Color(242, 227, 219));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 340, 40));

        hidere.setBackground(new java.awt.Color(242, 227, 219));
        hidere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png"))); // NOI18N
        hidere.setName(""); // NOI18N
        hidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidereActionPerformed(evt);
            }
        });
        jPanel1.add(hidere, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 40, 30));

        hidepass.setBackground(new java.awt.Color(242, 227, 219));
        hidepass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png"))); // NOI18N
        hidepass.setName(""); // NOI18N
        hidepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidepassActionPerformed(evt);
            }
        });
        jPanel1.add(hidepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 750, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 64)); // NOI18N
        jLabel1.setText("BookMaster");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 23, 372, 182));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/6607 1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 285, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 768));

        setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reloginActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();        
    }//GEN-LAST:event_btn_reloginActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        if(validateSignup() == true){
            if(checkDuplicateUser() == false){
                InsertSignupDetails();
            }
            else{
                JOptionPane.showMessageDialog(this, "username already exist");
            }
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        if(checkDuplicateUser() == true){
            JOptionPane.showMessageDialog(this, "username already exist");
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void hidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidereActionPerformed
        if (hidere.isSelected()) {
            txt_repassword.setEchoChar((char) 0); // Show confirm password
            hidere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png")));
        } else {
            txt_repassword.setEchoChar('•'); // Hide confirm password
            hidere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png")));
        }
    }//GEN-LAST:event_hidereActionPerformed

    private void hidepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidepassActionPerformed
        if (hidepass.isSelected()) {
            txt_password.setEchoChar((char) 0); // Show password
            hidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png")));
        } else {
            txt_password.setEchoChar('•'); // Hide password
            hidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png")));

        }
    }//GEN-LAST:event_hidepassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_relogin;
    private rojerusan.RSMaterialButtonRectangle btn_signup;
    private javax.swing.JCheckBox hidepass;
    private javax.swing.JCheckBox hidere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_repassword;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
